#! /bin/sh

if [ -x $HOME/program/dual.sh ];then
   ~/program/dual.sh
fi

bash ~/polybar-collection/launch.sh &

pgrep -x sxhkd > /dev/null || sxhkd &




  if [[ $(xrandr -q | grep "HDMI1 connected") ]];
  then
      xrandr --output HDMI1 --primary --mode 1920x1080 --rotate normal --output eDP1 --mode 1920x1080 --rotate normal --left-of HDMI1
      
      bspc monitor eDP1 -d I II III IV V 
      bspc monitor HDMI1 -d VI VII VIII IX X 

  else
      bspc monitor eDP1 -d I II III IV V VI VII VIII IX X
  fi






bspc config border_width         1
bspc config window_gap          4

bspc config single_monocle true
bspc config left_monocle_padding 1
bspc config right_monocle_padding 1
bspc config top_monocle_padding 1
bspc config bottom_monocle_padding 1

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

/home/boog/.fehbg &
picom &
/home/boog/programs/loginpaper/loginpaper.sh &
/home/boog/.cache/wal/colors.sh &
pulseaudio --start &
polybar &

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a brave desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Zathura state=tiled
